services:

  traefik:
    command:
      - "--log.level=DEBUG"
      - "--accessLog"
      - "--api=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.https.address=:443"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${HOST}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
